### PR TITLE
Fix instructions for setup

### PR DESCRIPTION
**Pull request by widforss**

### CODE REVIEW

**Review by Aleman778 — APPROVED** [review]
Good, might be also good to mention that you need either the md or lg model to get word vectors, the sm one does not include that.

**Comment by widforss** [comment]
> Good, might be also good to mention that you need either the md or lg model to get word vectors, the sm one does not include that.

Should we add all three? (It looks like they're automatically added to the conda env when I look at the .yml-file)

**Review by viktorfrom — APPROVED** [review]

**Review by markhakansson — APPROVED** [review]
lgtm

**Comment by Aleman778** [comment]
> 
> 
> > Good, might be also good to mention that you need either the md or lg model to get word vectors, the sm one does not include that.
> 
> Should we add all three? (It looks like they're automatically added to the conda env when I look at the .yml-file)

No we don't want all three but the large one might be slower to train, so I was thinking of just using the medium one for development and then switch to larger one when producing the final model.

**Comment by 97gushan** [comment]
Pip could not find the spacy model so the creation of the conda env was breaking

**Pull request merged**
