### PR TITLE
186 contacts view

### LINKED ISSUE #186: Add a contacts view to the GUI
# Summary
In this view the user should be able to see their local contacts in `config/contacts.yaml` and edit them. The user should also be able to add new contacts using this view.

# Examples

# Context
Right now we have no way of doing it except editing the file directly.

### PR DESCRIPTION
**Pull request by Aleman778**
# Proposed changes
* Added contact view for managing locally stored contacts.
* Contacts can now be created, edited and removed from the GUI.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- Test create some new contact, try renaming it and changing email also make sure to check contacts.yaml and compare. Finally, test deleting the contact and see that it is gone in contacts.yaml.

# Related issue
Fixes #186 

# Checkboxes
- [x] I have run the unit tests with `pytest`
- [x] I formatted the changes with `./scripts/formatter.sh`

### CODE REVIEW

**Review by markhakansson — APPROVED** [review]

**Comment by Blinningjr** [comment]
I can't remove the new contact I have created, but the old ones I can remove.

**Comment by hugowangler** [comment]
> I can't remove the new contact I have created, but the old ones I can remove.
> 
> My new contact:
> Name:niklas test
> Email:[test@testln.com](mailto:test@testln.com)

Can't seem to reproduce, working for me

**Review by hugowangler — APPROVED** [review]

**Review by viktorfrom — APPROVED** [review]
Tested, LGTM.

**Comment by viktorfrom** [comment]
> I can't remove the new contact I have created, but the old ones I can remove.
> 
> My new contact:
> Name:niklas test
> Email:[test@testln.com](mailto:test@testln.com)
Can't seem to reproduce this error either.

**Pull request merged**
