### PR TITLE
175 gui followup

### LINKED ISSUE #175: Improve GUI module followup handling
# Description
Currently, the followup system only handles the followups by displaying the message to the user. But now that there is support for retrieving mode information about a given followup the GUI should take advantage of this by prompting the user to answer the  followup easily without manually typing in the response.

### PR DESCRIPTION
**Pull request by Aleman778**
# Proposed changes
* Followups are now handled by the GUI, popup modal window is used to prompt the user.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- Test writing something very unspecific like `send email`, then for recipient you can write `John` so that you are also prompted to choose which contact to send to. The content of the email is has to also be written in the followup. That should result in three consecutive followups. The implementation relies heavily on callbacks and exception handling is tricky to do properly there so expect bugs.

# Related issue
Fixes #175 

# Checkboxes
- [x] I have run the unit tests with `pytest`
- [x] I formatted the changes with `./scripts/formatter.sh`

### CODE REVIEW

**Comment by Blinningjr** [comment]
When I write something random like "fsafdsfs" the text just disappears and no information is displayed to the user.

Do we have an issue addressing this?

**Comment by viktorfrom** [comment]
When attempting to create a task "send an email to john about food" which is an invalid recipient you get the response "Can only handle one (1) receiver at this time". Something like "invalid receiver" would probably be a more appropriate response.

**Comment by Aleman778** [comment]
> 
> 
> When I write something random like "fsafdsfs" the text just disappears and no information is displayed to the user.
> 
> Do we have an issue addressing this?

Very strange It should have popped up an error saying that it failed to parse the sentence. For some reason the callback I used to create the tasks in the GUI is not fired.

**Comment by Aleman778** [comment]
> 
> 
> When attempting to create a task "send an email to john about food" which is an invalid recipient you get the response "Can only handle one (1) receiver at this time". Something like "invalid receiver" would probably be a more appropriate response.

This is not an issue in the GUI, maybe put a new Issue on this for the automation?

**Comment by Aleman778** [comment]
> 
> 
> When I write something random like "fsafdsfs" the text just disappears and no information is displayed to the user.
> 
> Do we have an issue addressing this?

This should now give an error message.

**Comment by Aleman778** [comment]
There is a bug with editing tasks, it just creates a new task instead. Wait until that is fixed before merging.

**Comment by viktorfrom** [comment]
> > When attempting to create a task "send an email to john about food" which is an invalid recipient you get the response "Can only handle one (1) receiver at this time". Something like "invalid receiver" would probably be a more appropriate response.
> 
> This is not an issue in the GUI, maybe put a new Issue on this for the automation?

Never mind, ignore my previous comment, this seems to be a RPA-model problem. "food" is tagged as a recipient which prompts the response.

**Review by Blinningjr — APPROVED** [review]

**Review by markhakansson — APPROVED** [review]
Tested and works! Looks good :)

**Pull request merged**
