### PR TITLE
134 gui design view

### LINKED ISSUE #134: Finish up the GUI for the design view
# Description
The design view (temp. name) is where the user can create a process by inputting text into the top field. When the user enters text, the view below visualize what will happen when the process is executed. The user should also correct mistakes made in this visualization view and alter the order of operations.

# Features
- [x] the order of operations should be modified by e.g. disconnecting and reconnecting process blocks
- [x] add submit button next to the top text field, currently only enter can be used to submit the text
- [x] box selector to select multiple items should be possible, also add copy and paste functionality
- [x] editing entered queries should be possible appropriately
- [ ] datetime currently uses absolute time which is annoying when certain tasks should be repeated
- [ ] LATER (wait for new followup system) improve the way followups are handled, no contacts found should be handled 
- [ ] optional: would be nice to be able to zoom in and out in the view
- [ ] optional: autocompletion of contacts
- [ ] optional: task piping #131 should create the correct number of blocks

### PR DESCRIPTION
**Pull request by Aleman778**
# Proposed changes
* Improved the overall GUI focusing on the Design View part
* Processes can now be connected, edited, saved and loaded (using Ctrl-S/ Ctrl-F)
* Fixed bugs in the GUI

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- Manual testing of the features added
- Use Ctrl-S for saving and Ctrl-F for loading (temporary keybindings)

# Related issue
Fixes #134

# Checkboxes
- [ ] I have run the unit tests with `pytest`
- [x] I formatted the changes with `./scripts/formatter.sh`

### CODE REVIEW

**Review by viktorfrom — APPROVED** [review]
lgtm

**Comment by Blinningjr** [comment]
I get this error when I type in the body of a reminder.
`TypeError: setBody() missing 1 required positional argument: 'text'`

Should probably fix that before merging

**Comment by Blinningjr** [comment]
I am not able to save.

**Comment by Aleman778** [comment]
> 
> 
> I am not able to save processes.

Did Ctrl-S and Ctrl-F not work?
The save/load interface is not done right now.

**Review by Blinningjr — APPROVED** [review]

**Pull request merged**
